### ISSUE TITLE
Possible typo in documentation for conda activation

### ISSUE THREAD

**Issue by djbrock** [DeDop/dedop#6]
Docs/Installation/From Source says

```
conda create -n dedop python=3
source activate.sh dedop
```

command actually needed (using Anaconda on OSX) was

```
source activate dedop
```

might be because I used Anaconda rather than Miniconda?

**Comment by mark-ep** [comment]
`source activate.sh dedop` works for me on linux, but I have found that when using either Anaconda or Miniconda on windows, I need to use `activate dedop`. Is anyone aware of any other commands that might be platform-specific?

**Comment by hans-permana** [comment]
@djbrock  Yes, it should have been `source activate dedop` in OSX or Unix. I will fix the documentation and also add more information for other OS-specific commands.

@mark-ep do you use MiniConda or Anaconda? I tried `source activate.sh dedop` and it didn't work. I am using MiniConda in my Ubuntu VM.
